CREATE TABLE IF NOT EXISTS LOGS (
    SOLVENUM SERIAL PRIMARY KEY,
    ID TEXT,
    REQUEST TEXT,
    POST_TXT TEXT,
    POST_URL TEXT,
    STATUS VARCHAR(10),
    IP VARCHAR(45),
    SOLVE_TIME NUMERIC,
    EXE NUMERIC,
    MEMO NUMERIC,
    FLUIDNESS NUMERIC,
    DATE TIMESTAMP,
    SUCCESS BOOLEAN,
    ERROR TEXT
);
