CREATE TABLE IF NOT EXISTS LOGS (
    SOLVENUM SERIAL PRIMARY KEY,
    ID TEXT,
    REQUEST TEXT,
    POST_TXT TEXT,
    POST_URL TEXT,
    STATUS VARCHAR(10),
    IP VARCHAR(45),
    SOLVE_TIME NUMERIC,
    EXE NUMERIC,
    MEMO NUMERIC,
    FLUIDNESS NUMERIC,
    DATE TIMESTAMP,
    SUCCESS BOOLEAN,
    ERROR TEXT,
    SOLVE_METADATA JSONB,
    TOTAL_MOVES NUMERIC,
    TOTAL_ALGS NUMERIC,
    TPS NUMERIC,
    TOTAL_PAUSES NUMERIC
);

CREATE TABLE IF NOT EXISTS SESSIONS (
    SESSION_ID SERIAL PRIMARY KEY,
    USER_ID TEXT NOT NULL,
    NAME TEXT NOT NULL,
    PUZZLE_TYPE TEXT DEFAULT '3x3 BLD',
    SCRAMBLE_TYPE TEXT DEFAULT '3x3',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SESSIONS_USER_UPDATED
    ON SESSIONS (USER_ID, UPDATED_AT DESC);

CREATE TABLE IF NOT EXISTS SOLVES (
    SOLVE_ID SERIAL PRIMARY KEY,
    SESSION_ID INTEGER NOT NULL REFERENCES SESSIONS(SESSION_ID) ON DELETE CASCADE,
    USER_ID TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SOLVE_TIME NUMERIC,
    EXE NUMERIC,
    MEMO NUMERIC,
    FLUIDNESS NUMERIC,
    SUCCESS BOOLEAN,
    DNF BOOLEAN DEFAULT FALSE,
    PARSED_TXT TEXT,
    PARSED_URL TEXT,
    SCRAMBLE TEXT,
    SOLVE_TEXT TEXT,
    REQUEST_JSON JSONB,
    SOLVE_METADATA JSONB,
    TOTAL_MOVES NUMERIC,
    TOTAL_ALGS NUMERIC,
    TPS NUMERIC,
    TOTAL_PAUSES NUMERIC
);

CREATE INDEX IF NOT EXISTS IDX_SOLVES_SESSION_CREATED
    ON SOLVES (SESSION_ID, CREATED_AT DESC);

CREATE INDEX IF NOT EXISTS IDX_SOLVES_USER_CREATED
    ON SOLVES (USER_ID, CREATED_AT DESC);

CREATE TABLE IF NOT EXISTS SOLVE_COMMS (
    COMM_ID SERIAL PRIMARY KEY,
    SOLVE_ID INTEGER NOT NULL REFERENCES SOLVES(SOLVE_ID) ON DELETE CASCADE,
    COMM_INDEX INTEGER NOT NULL,
    COMM_PHASE TEXT NOT NULL,
    BUFFER_TARGET TEXT,
    TARGET_A TEXT,
    TARGET_B TEXT,
    SPECIAL_TYPE TEXT,
    PIECE_TYPE TEXT,
    RECOG_TIME NUMERIC,
    EXEC_TIME NUMERIC,
    ALG TEXT,
    ALG_LENGTH INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SOLVE_COMMS_SOLVE_INDEX
    ON SOLVE_COMMS (SOLVE_ID, COMM_INDEX);

CREATE TABLE IF NOT EXISTS SOLVE_MOVES (
    MOVE_ID SERIAL PRIMARY KEY,
    SOLVE_ID INTEGER NOT NULL REFERENCES SOLVES(SOLVE_ID) ON DELETE CASCADE,
    MOVE_INDEX INTEGER NOT NULL,
    NOTATION TEXT,
    TIME_OFFSET NUMERIC,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_SOLVE_MOVES_SOLVE_INDEX
    ON SOLVE_MOVES (SOLVE_ID, MOVE_INDEX);
