worker_processes auto;

events {
    worker_connections 1024;
}

http {
    #include       /etc/nginx/mime.types;
    #default_type  application/octet-stream;

    # Include the server block here or reference it via another file
    server {
        listen 80;
        server_name trainbld.com www.trainbld.com;

        # Serve the React Website
        location / {

	    root /usr/share/nginx/html;
            proxy_pass http://trainbld_website:80;  # Forward to the frontend service
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            try_files $uri /index.html;  # Ensure React routes are handled properly
        }

        # Proxy requests to the Flask backend
        location /parse {
            proxy_pass http://trainbld_server:8080;  # Forward to the backend service
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Proxy requests to Adminer
        location /adminer {
            proxy_pass http://adminer:8080;  # Forward to the Adminer service
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
